--
-- PostgreSQL database dump
--

\restrict eOEHXZsCrokDYKUTgEt8kSoKlDy48etsKsdvfRSWiKrscLOJeyPmJZ0uCzZ0GTU

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_userview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_userview (
    id bigint NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_userview OWNER TO postgres;

--
-- Name: users_userview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_userview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_userview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-31 21:00:21.452433+00
2	contenttypes	0002_remove_content_type_name	2026-05-31 21:00:21.460965+00
3	auth	0001_initial	2026-05-31 21:00:21.476178+00
4	auth	0002_alter_permission_name_max_length	2026-05-31 21:00:21.48473+00
5	auth	0003_alter_user_email_max_length	2026-05-31 21:00:21.495334+00
6	auth	0004_alter_user_username_opts	2026-05-31 21:00:21.505026+00
7	auth	0005_alter_user_last_login_null	2026-05-31 21:00:21.516693+00
8	auth	0006_require_contenttypes_0002	2026-05-31 21:00:21.522913+00
9	auth	0007_alter_validators_add_error_messages	2026-05-31 21:00:21.534122+00
10	auth	0008_alter_user_username_max_length	2026-05-31 21:00:21.545323+00
11	auth	0009_alter_user_last_name_max_length	2026-05-31 21:00:21.557972+00
12	auth	0010_alter_group_name_max_length	2026-05-31 21:00:21.56639+00
13	auth	0011_update_proxy_permissions	2026-05-31 21:00:21.57193+00
14	auth	0012_alter_user_first_name_max_length	2026-05-31 21:00:21.582223+00
15	users	0001_initial	2026-05-31 21:00:21.594552+00
16	admin	0001_initial	2026-05-31 21:00:21.60559+00
17	admin	0002_logentry_remove_auto_add	2026-05-31 21:00:21.625693+00
18	admin	0003_logentry_add_action_flag_choices	2026-05-31 21:00:21.641127+00
19	sessions	0001_initial	2026-05-31 21:00:21.648343+00
20	users	0002_userview	2026-05-31 21:00:21.6665+00
21	users	0003_update_roles	2026-05-31 21:00:21.671915+00
22	users	0004_user_event_outbox	2026-05-31 21:00:21.682878+00
\.


--
-- Data for Name: users_userview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_userview (id, username, email, created_at) FROM stdin;
2	andres	andres@gmail.com	2026-05-31 21:02:07.355559+00
3	andres2	andres2@gmail.com	2026-06-10 22:10:17.084922+00
4	ariel	ariel@gmail.com	2026-06-10 22:48:45.698708+00
5	andressss	andres5@test.com	2026-06-11 04:48:51.580247+00
6	codex_1781153355129	codex_1781153355129@example.com	2026-06-11 04:49:15.798725+00
7	ui_guest_1781153646128	ui_guest_1781153646128@example.com	2026-06-11 04:54:08.748216+00
8	ui_guest_1781153796718	ui_guest_1781153796718@example.com	2026-06-11 04:56:39.048409+00
9	ui_guest_1781153934513	ui_guest_1781153934513@example.com	2026-06-11 04:58:56.845854+00
10	ui_guest_1781154031349	ui_guest_1781154031349@example.com	2026-06-11 05:00:34.233764+00
11	jaime	jaime@test.com	2026-06-16 23:11:25.840822+00
12	guest_res_1782218045990	guest-res-1782218045990@example.com	2026-06-23 12:34:06.99055+00
13	host_res_1782218045990	host-res-1782218045990@example.com	2026-06-23 12:34:07.794525+00
14	guest_res_1782218081509	guest-res-1782218081509@example.com	2026-06-23 12:34:42.113734+00
15	host_res_1782218081509	host-res-1782218081509@example.com	2026-06-23 12:34:42.647787+00
16	guest_neg_1782218115939	guest-neg-1782218115939@example.com	2026-06-23 12:35:16.736659+00
17	host_neg_1782218115939	host-neg-1782218115939@example.com	2026-06-23 12:35:17.423817+00
18	test_reservas_20260623191158	test_reservas_20260623191158@example.com	2026-06-23 23:11:59.252411+00
19	guest_flow_20260623191226	guest_flow_20260623191226@example.com	2026-06-23 23:12:27.277899+00
20	host_flow_20260623191226	host_flow_20260623191226@example.com	2026-06-23 23:12:27.788921+00
21	mau	mau@test.com	2026-06-23 23:15:35.175223+00
\.


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: users_userview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_userview_id_seq', 1, false);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: users_userview users_userview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_userview
    ADD CONSTRAINT users_userview_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict eOEHXZsCrokDYKUTgEt8kSoKlDy48etsKsdvfRSWiKrscLOJeyPmJZ0uCzZ0GTU

