spring.application.name=alojamientos

server.port=8081

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# Por ahora lo desactivamos para que no complique el arranque.
# Luego lo activamos con migraciones SQL.
# ===============================
spring.flyway.enabled=false

# ===============================
# BASE DE DATOS DE ESCRITURA
# ===============================
app.datasource.write.url=jdbc:postgresql://localhost:5432/alojamientos_write_db
app.datasource.write.username=postgres
app.datasource.write.password=root
app.datasource.write.driver-class-name=org.postgresql.Driver

# ===============================
# BASE DE DATOS DE LECTURA
# ===============================
app.datasource.read.url=jdbc:postgresql://localhost:5432/alojamientos_read_db
app.datasource.read.username=postgres
app.datasource.read.password=root
app.datasource.read.driver-class-name=org.postgresql.Driver

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info